# Generated by Django 6.0.5 on 2026-05-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='daily_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='daily_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='last_reset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
